### ISSUE TITLE
Document DCO signed-off-by requirement?

### ISSUE THREAD

**Issue by wking** [kubernetes/kubernetes-template-project#16]
The [CNCF charter][1] has (§11.c):

> All new inbound code contributions to the CNCF shall be (i) accompanied by a Developer Certificate of Origin sign-off (http://developercertificate.org) and (ii) made under the Apache License, Version 2.0 (available at http://www.apache.org/licenses/LICENSE-2.0), such license to be in addition to, and shall not supersede, obligations undertaken under the contribution license agreement(s) provided for in (b) above.

But the `CONTRIBUTING.md` file in this repository currently only mentions the CLA ~~(which is optional per-project, as discussed in §11.b)~~.  It should probably be expanded to include the DCO and Signed-off-by docs (I have [a project for including stock docs][2], or you can write your own) to comply with §11.c, ~~and may deserve a note (in the docs requested in #2?) to point out that project owners can remove the CLA requirement if they want~~ [EDIT: CLAs are [not optional][3] for Kubernetes projects].

[1]: https://www.cncf.io/about/charter/
[2]: https://github.com/wking/signed-off-by
[3]: https://github.com/kubernetes/kubernetes-template-project/issues/16#issuecomment-377096061

**Comment by cblecker** [comment]
cc: @kubernetes/steering

**Comment by cblecker** [comment]
cc: @kubernetes/steering-committee

**Comment by bgrant0607** [comment]
All of Kubernetes uses CLA.

**Comment by wking** [comment]
> All of Kubernetes uses CLA.

That simplifies things; it will just be CLA + DCO for all contributions.

**Comment by bgrant0607** [comment]
@caniszczyk Is the intent to require DCO of all projects, even those which use CLA?

**Comment by wking** [comment]
Anything I can do to help this along?

**Comment by philips** [comment]
I don't think there is any intention to add a DCO requirement to Kubernetes given the CLA requirement. If the CNCF needs to update language please add it to the next CNCF GB agenda @caniszczyk.

/close
