### ISSUE TITLE
Document recommended repo setup

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes-template-project#2]
Forked from https://github.com/kubernetes/kops/issues/644

I think it would be useful to describe the recommended setup for repos in the template.

For example, admin and maintainers (write) teams.

And how to turn on the bot. And copy labels.

And OWNERS.

Etc

cc @grodrigues3

**Comment by bgrant0607** [comment]
In the kubernetes-incubator org, ACL teams are named admins-repo and maintainers-repo. I prefer repo-admins (admin), repo-maintainers (write), and repo-collaborators (read). The teams are sorted alphabetically on the github UI, so putting the repo first groups them together. It's also handier for auto-completion.

**Comment by philips** [comment]
@sarahnovotny I think I wrote something somewhere at sometime. Do you remember where we put that?

**Comment by bgrant0607** [comment]
@spiffxp is working on related issues

**Comment by spiffxp** [comment]
/close
This is halfway done by docs in https://github.com/kubernetes/community/tree/master/github-management and I'd rather keep issues related to editing that over there
