### ISSUE TITLE
Please update the LICENSE with the copyright holder

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes-template-project#3]
It should be "The Kubernetes Authors".

Most repos haven't modified the boilerplate `Copyright {yyyy} {name of copyright owner}`

**Comment by philips** [comment]
I don't think license files should be updated. I think we discussed this in person at KubeCon with @jbeda. 

I will close for now.

**Comment by jbeda** [comment]
IIRC the Google lawyers say that we shouldn't modify the LICENSE file itself but instead just do that substitution when applying to individual files.  See https://github.com/kubernetes/kubernetes/pull/883.  Note that this got merged in the main repo at some point and should probably be reverted.

**Comment by philips** [comment]
Hrm, you are right @jbeda. I will put up a PR to try and revert.

**Comment by philips** [comment]
As discussed: https://github.com/kubernetes/kubernetes/pull/37305

**Comment by Ring2381** [comment]
Let me findbout its you mfs  on my phone. Anf if Youve breached anyone else in my family, you just illegally had accessed a major tobaccoo comp info...

**Comment by mehrad139** [comment]
LICENSE
